# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 19:06
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, verbose_name='Área')),
            ],
            options={
                'verbose_name_plural': '02 - Áreas',
                'verbose_name': 'Área',
            },
        ),
        migrations.CreateModel(
            name='Assessores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo')),
                ('foto', models.ImageField(upload_to='assessor/%y/%m/%d', verbose_name='Foto')),
            ],
            options={
                'verbose_name_plural': '07 - Assessores',
                'verbose_name': 'Assessor',
            },
        ),
        migrations.CreateModel(
            name='ClienteNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name_plural': '08 - Newsletter',
                'verbose_name': 'Newsletter',
            },
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do diretor')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('foto', models.ImageField(upload_to='diretor/%y/%m/%d', verbose_name='Foto do diretor')),
            ],
            options={
                'verbose_name_plural': '06 - Diretores',
                'verbose_name': 'Diretor',
            },
        ),
        migrations.CreateModel(
            name='EmpresaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100, verbose_name='Nome da empresa')),
                ('foto_empresa', models.ImageField(upload_to='empresa/%y/%m/%d', verbose_name='Foto da empresa')),
                ('email_empresa', models.EmailField(max_length=254, verbose_name='E-mail da empresa')),
                ('facebook', models.CharField(max_length=200, verbose_name='Facebook da empresa')),
            ],
            options={
                'verbose_name_plural': '04 - Empresas',
                'verbose_name': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='Eventos', verbose_name='Foto')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': '09 - Eventos',
                'verbose_name': 'Evento',
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=200, verbose_name='Subtítulo')),
                ('criado', models.DateTimeField(default=django.utils.timezone.now, validators=[home.validators.validador_de_data])),
                ('texto', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(help_text='Link da notícia. Não usar caracteres com acentos ou caracteres especiais.', max_length=100, unique=True, verbose_name='Link')),
                ('imagem', models.ImageField(upload_to='noticias/%y/%m/%d', verbose_name='Imagem')),
                ('data_orientation', models.CharField(blank=True, max_length=100)),
                ('data_slice_1', models.SmallIntegerField(blank=True, null=True)),
                ('data_slice_2', models.SmallIntegerField(blank=True, null=True)),
                ('data_slice_1_scale', models.FloatField(blank=True, null=True)),
                ('data_slice_2_scale', models.FloatField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '01 - Notícias',
                'verbose_name': 'Notícia',
            },
        ),
        migrations.CreateModel(
            name='Parceiros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='parceiros/%y/%m/%d', verbose_name='Imagem')),
                ('titulo', models.CharField(help_text='Para ajudar a ver as empresas na listagem.', max_length=100, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Texto')),
            ],
            options={
                'verbose_name_plural': '05 - Parceiros',
                'verbose_name': 'Parceiro',
            },
        ),
        migrations.CreateModel(
            name='SetorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor')),
                ('area_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.AreaModel')),
            ],
            options={
                'verbose_name_plural': '03 - Setores',
                'verbose_name': 'Setor',
            },
        ),
        migrations.AddField(
            model_name='empresamodel',
            name='setor_referencia',
            field=models.ManyToManyField(to='home.SetorModel'),
        ),
        migrations.AddField(
            model_name='assessores',
            name='diretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Diretor'),
        ),
    ]
