# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do cliente')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail do cliente')),
            ],
            options={
                'verbose_name_plural': 'Newsletter',
                'verbose_name': 'Newsletter',
            },
        ),
    ]
