# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='visivel',
            field=models.BooleanField(default=True, verbose_name='Visível'),
        ),
    ]
