# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-21 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientenewsletter',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='clientenewsletter',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
