# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 14:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='criado',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 14, 46, 4, 973476, tzinfo=utc)),
        ),
    ]
