# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 03:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170921_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamodel',
            name='email_empresa',
            field=models.EmailField(default=datetime.datetime(2017, 9, 27, 3, 14, 26, 484454, tzinfo=utc), max_length=254, verbose_name='E-mail da empresa'),
            preserve_default=False,
        ),
    ]
