# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-01 13:23
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_noticias_visivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextoRN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', ckeditor.fields.RichTextField()),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': '10 - Textos da RN',
                'verbose_name': 'Texto da RN',
            },
        ),
    ]
