# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 15:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_noticias_criado'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessores',
            name='cargo',
            field=models.CharField(default=datetime.datetime(2017, 10, 13, 15, 16, 17, 809281, tzinfo=utc), max_length=200, verbose_name='Cargo do assessor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticias',
            name='criado',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 15, 16, 14, 46269, tzinfo=utc)),
        ),
    ]
