# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-02 15:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_empresamodel_email_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 10, 2, 15, 1, 33, 723730, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(default=datetime.datetime(2017, 10, 2, 15, 2, 7, 66781, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
