# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 15:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171013_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parceiros',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='noticias',
            name='criado',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 15, 24, 24, 591256, tzinfo=utc)),
        ),
    ]
