# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-02 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171002_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
