# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_parceiros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inteiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='parceiros',
            options={'verbose_name': 'Parceiro'},
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagem',
            field=models.ImageField(upload_to='%y/%m/%d', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='parceiros',
            name='foto',
            field=models.ImageField(upload_to='%y/%m/%d', verbose_name='Imagem'),
        ),
    ]
