# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 15:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171013_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiros',
            name='titulo',
            field=models.CharField(default=datetime.datetime(2017, 10, 13, 15, 31, 54, 795915, tzinfo=utc), help_text='Para ajudar a ver as empresas na listagem.', max_length=100, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticias',
            name='criado',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 15, 31, 50, 764111, tzinfo=utc)),
        ),
    ]
