# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170829_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='texto_teste',
            field=models.CharField(default=datetime.datetime(2017, 8, 29, 21, 8, 19, 170254, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
