# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-09 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20171002_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='data_slice_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='data_slice_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='slug',
            field=models.SlugField(help_text='Link da notícia. Não usar caracteres com acentos ou caracteres especiais.', max_length=100, unique=True, verbose_name='Link'),
        ),
    ]
