# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 15:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20171013_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='Eventos', verbose_name='Foto')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.AlterField(
            model_name='noticias',
            name='criado',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 15, 35, 52, 268828, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='parceiros',
            name='titulo',
            field=models.CharField(help_text='Para ajudar a ver as empresas na listagem.', max_length=100, verbose_name='Título'),
        ),
    ]
