# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20171009_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='data_slice_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='data_slice_2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
