# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_noticias_texto_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='texto_teste',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
