# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-30 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170829_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, verbose_name='Área')),
            ],
        ),
        migrations.CreateModel(
            name='SetorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor')),
                ('area_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.AreaModel')),
            ],
        ),
    ]
