# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-30 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_areamodel_setormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100, verbose_name='Nome da empresa')),
            ],
        ),
        migrations.AlterModelOptions(
            name='areamodel',
            options={'verbose_name': 'Área'},
        ),
        migrations.AlterModelOptions(
            name='setormodel',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AddField(
            model_name='empresamodel',
            name='setor_referencia',
            field=models.ManyToManyField(to='home.SetorModel'),
        ),
    ]
