# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-30 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170830_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresamodel',
            options={'verbose_name': 'Empresa'},
        ),
    ]
