# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-30 18:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170830_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamodel',
            name='foto_empresa',
            field=models.ImageField(default=datetime.datetime(2017, 8, 30, 18, 27, 6, 803570, tzinfo=utc), upload_to='%y/%m/%d', verbose_name='Foto da empresa'),
            preserve_default=False,
        ),
    ]
