# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-06 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_empresamodel_foto_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do assessor')),
            ],
            options={
                'verbose_name': 'Assessor',
                'verbose_name_plural': 'Assessores',
            },
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do diretor')),
            ],
            options={
                'verbose_name': 'Diretor',
                'verbose_name_plural': 'Diretores',
            },
        ),
        migrations.AddField(
            model_name='assessores',
            name='diretor_referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Diretor'),
        ),
    ]
