# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-06 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170906_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessores',
            name='foto',
            field=models.ImageField(default=datetime.datetime(2017, 9, 6, 19, 12, 13, 746297, tzinfo=utc), upload_to='assessor/%y/%m/%d', verbose_name='Foto do assessor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diretor',
            name='foto',
            field=models.ImageField(default=datetime.datetime(2017, 9, 6, 19, 12, 23, 441623, tzinfo=utc), upload_to='diretor/%y/%m/%d', verbose_name='Foto do diretor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresamodel',
            name='foto_empresa',
            field=models.ImageField(upload_to='empresa/%y/%m/%d', verbose_name='Foto da empresa'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagem',
            field=models.ImageField(upload_to='noticias/%y/%m/%d', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='parceiros',
            name='foto',
            field=models.ImageField(upload_to='parceiros/%y/%m/%d', verbose_name='Imagem'),
        ),
    ]
