# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-06 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20170906_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticias',
            old_name='texto_teste',
            new_name='data_orientation',
        ),
    ]
