# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-06 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20170906_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='data_slice_1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticias',
            name='data_slice_1_scale',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticias',
            name='data_slice_2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticias',
            name='data_slice_2_scale',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
