# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-06 20:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20170906_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='modificado',
            field=models.BooleanField(default=datetime.datetime(2017, 9, 6, 20, 10, 24, 849733, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
