# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-06 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_noticias_modificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='modificado',
            field=models.BooleanField(default=False),
        ),
    ]
