# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20170906_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresamodel',
            name='setor_referencia',
            field=models.ManyToManyField(related_name='teste', to='home.SetorModel'),
        ),
    ]
